### ISSUE TITLE
Add support for websockets

### ISSUE THREAD

**Issue by tionis** [CosmicToast/jurl#1]
Currently, it's not possible to use jurl to create websocket connections as it's not exposed over libcurl's easy API

**Comment by CosmicToast** [comment]
If your linked libcurl is built with websocket support, it should already be possible via the easy api via `jurl/native`.
```janet
(import jurl/native)
(def client (native/new))
(put client :url "wss://ws.example.com")
(put client :writefunction some-func)
(put client :readfunction some-func)
(:perform client)
```
P.S. I have not tested this.

For further integration, the problem is that the functionality is [experimental](https://curl.se/libcurl/c/libcurl-ws.html).
Both the API and ABI might change, and the functionality is not available at all if libcurl is built without it.

I don't currently have the time to maintain something with that many moving parts, especially if it's going to be changed potentially at any moment, so I can't add this for now.
Presuming the API stays as it is and becomes a core part of curl later, it shouldn't be too hard to actually add the connect model: `curl_ws_send` and `curl_ws_recv` can essentially be abstracted to read/write calls like a regular janet socket.

**Comment by tionis** [comment]
Ok, thanks, I'll try it out.
I'll close it for now and maybe open a new one when web sockets are no longer marked as experimental.
